# Generated by Django 5.0.7 on 2024-07-18 15:27

import ckeditor5.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre del Cliente')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido del Cliente')),
                ('phone', models.CharField(max_length=30, verbose_name='Teléfono del Cliente')),
                ('email', models.EmailField(max_length=50, verbose_name='Email del Cliente')),
                ('password', models.CharField(max_length=50, verbose_name='Contraseña del Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre de la Categoria')),
                ('description', ckeditor5.fields.RichTextField(max_length=250, verbose_name='Descripcion del Producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto')),
                ('image', models.ImageField(upload_to='uploads/product', verbose_name='Imagen del Producto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
