# Generated by Django 5.0.7 on 2024-07-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brand_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Código del Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripcion del Producto'),
        ),
    ]
