# Generated by Django 5.0.7 on 2024-07-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_codigo_product_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del País')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Número de Orden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(default=1, verbose_name='Contenido del Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default=1, max_length=100, verbose_name='Origen del Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Descripción del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Producto'),
        ),
    ]
