# Generated by Django 5.0.7 on 2024-07-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_country_order_order_number_product_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(default=1, verbose_name='Descripción de la Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.country', verbose_name='País Origen del Producto'),
        ),
    ]
