# Generated by Django 5.0.7 on 2024-07-18 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category_content_alter_product_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__order', 'order'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category', verbose_name='Categoría Principal'),
        ),
    ]
