# Generated by Django 5.0.7 on 2024-07-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_product_codigo_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='En Oferta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
