# Generated by Django 5.0.7 on 2024-07-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
