# Generated by Django 5.0.7 on 2024-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, default='', max_length=100, verbose_name='Dirección'),
        ),
    ]
